### ISSUE TITLE
not compatible with Dart SDK version 2.2.1

### ISSUE THREAD

**Issue by felipaoo** [seenickcode/pure_mixpanel#5]
While installing package dependencies, I got this message:

```bash
Because pure_mixpanel 1.0.6 requires SDK version >=1.19.0 <=2.2.0 and no versions of pure_mixpanel match >1.0.6 <2.0.0, pure_mixpanel ^1.0.6 is forbidden.
So, because cuenca_mobile depends on pure_mixpanel ^1.0.6, version solving failed.
```

my Dart SDK Version is 2.2.1-dev.0.0.flutter-571ea80e11

**Comment by seenickcode** [comment]
Merged and published. v1.0.7 now. Thanks @felipaoo and @olivierbrand

**Comment by prakashraman** [comment]
Thanks!

Although I dont see `1.0.7` in the releases page. 

https://github.com/seenickcode/pure_mixpanel/releases
