### ISSUE TITLE
How to use this in production?

### ISSUE THREAD

**Issue by kbrmimbyl** [seenickcode/pure_mixpanel#7]
I'm having trouble understanding how to use this plugin in production... can you pls give some pointers?

**Comment by Nash0x7E2** [comment]
Hi, 
To use in production, you can create a new instance of Mixpanel:
```
   final panel = Mixpanel(
      token: your-token,
      trackIp: true,
      debug: isInDebugMode,
      showDebugLog: false
    ),
```

Then call `panel.tack(your-event-name)` from places in your app where you'd like to send events to Mixpanel. 

Hope this helps, 
Nash

**Comment by kbrmimbyl** [comment]
Thanks, will check it out.
